POST http://localhost:3000/admin/pages/add-page
Content-Type: application/json

{
  "title": "", 
  "slug": "password",
  "content": ""
}
###
POST http://localhost:3000/admin/products/add-products
Content-Type: application/json

{
  "title": "", 
  "slug": "password",
  "content": ""
}